### ISSUE TITLE
[BUG]:Arduino Uno can not recognize the As5047p

### ISSUE THREAD

**Issue by tweikid** [jonas-merkle/AS5047P#38]
**Describe the bug**
The library and code work perfectly with Arduino Mega, but can not recognize the As5047p when linked with Arduino Uno. The only feedback from the monitor is the error message. I tried three different Arduino Uno. None worked.

**To Reproduce**
1. As the library said, I connected pins as follow: 5v-5v; GND-GND; MOSI-11; MISO-12; CLK-13; CSN-9
2. Used the code "BasicReadAngle" from Github.
3. The Serial monitor only outputs the error message saying: "Can't connect to the AS5047P sensor! Please check the connection..."

**Expected behavior**
The serial monitor reads and outputs the angle data from the As5047p sensor. 

**Arduino (please complete the following information):**
 - Arduino Uno
 - Arduino  1.8.17
 - The Version of this Library 2.1.5

**Hardware Setup (please complete the following information):**
 - As the library said, I connected pins as follow: 5v-5v; GND-GND; MOSI-11; MISO-12; CLK-13; CSN-9

**Additional context**
I have no idea where I did wrong for the Arduino not recognizing the sensor. I borrowed an Arduino Mega and it worked. However, when I use Arduino Uno it does not.

**Comment by jonas-merkle** [comment]
Hi @tweikid 

I'm sorry to hear that you are having such problems with the Arduino Uno and the sensor. 

At the moment, I'm also a bit stumped as to what's causing the problem for you. 
Just to make sure we are talking about the same thing:
- You are using an original Arduino Uno.
- It is not a 3.3V version of the Arduino Uno.
- There are no Arduino Shilds or other sensors connected to the Arduino.
- The sensor (including cabling) works in conjunction with an Arduino Mega without any problems.

All the best
Jonas
