### ISSUE TITLE
[BUG]: Error Compiling for board Teensy 4.1

### ISSUE THREAD

**Issue by Btreasoner** [jonas-merkle/AS5047P#41]
**Describe the bug**
Not able to compile the "BasicReadAngle" example.

**Error Message**
Arduino: 1.8.19 (Windows 10), TD: 1.57, Board: "Teensy 4.1, Serial, 600 MHz, Faster, US English"

In file included from D:\0-Files\Documents\Arduino\libraries\AS5047P\src\types\AS5047P_Types.cpp:12:0:

D:\0-Files\Documents\Arduino\libraries\AS5047P\src\types\AS5047P_Types.h:140:18: error: 'string' in namespace 'std' does not name a type

             std::string toStdString();

                  ^

D:\0-Files\Documents\Arduino\libraries\AS5047P\src\types\AS5047P_Types.cpp:35:38: error: no 'std::__cxx11::string AS5047P_Types::ERROR_t::toStdString()' member function declared in class 'AS5047P_Types::ERROR_t'

     std::string ERROR_t::toStdString() {

                                      ^

Error compiling for board Teensy 4.1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by jonas-merkle** [comment]
Hey @Btreasoner,
thanks for your feedback. I changed the way in which the this library handles c++ strings. (see #)
Just use the library manager within the Arduino IDE and update the library to the version >= 2.2.0 and you should be able to compile the example again without errors.
